x-base-php: &base-php
  build:
    context: ./php
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      PHP_VERSION: ${PHP_VERSION:-8.3}
      XDEBUG_VERSION: ${XDEBUG_VERSION:-3.3.1}
      DOCKER_HTTP_PORT: ${DOCKER_HTTP_PORT:-8080}
  env_file: .env
  working_dir: ${VOLUME_ROOT:-/var/www/html}
  volumes:
    - ../:${VOLUME_ROOT:-/var/www/html}
    - ./php/ini/symfony.ini:/usr/local/etc/php/conf.d/99-symfony.ini
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    COMPOSER_HOME: ${VOLUME_ROOT:-/var/www/html}/.composer
    COMPOSER_MEMORY_LIMIT: -1
    HOME: ${VOLUME_ROOT:-/var/www/html}
    XDEBUG_MODE: ${XDEBUG_MODE:-off}
    PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME:-my_awesome_project}
    XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}

services:
  php:
    <<: *base-php
    tty: true
    ports:
      - '${DOCKER_PORT_HTTP:-8080}:${DOCKER_PORT_HTTP:-8080}'
